"""Constants for Salus Controls."""

DOMAIN = "salus_controls"

MIN_TEMP = 5
MAX_TEMP = 34.5

FREEZE_PROTECTION_MIN_TEMP = 1
FREEZE_PROTECTION_MAX_TEMP = 9

TEMPERATURE_TOLERANCE_MIN = 0.25
TEMPERATURE_TOLERANCE_MAX = 3